# .github/workflows/release.yml
name: Build and Release to PyPI

on:
  release:
    types: [published]  # Se déclenche quand tu publies une release sur GitHub

permissions:
  contents: read

jobs:
  build:
    name: Build distribution 📦
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Récupère tout l'historique pour setuptools-scm si utilisé
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"
    
    - name: Install pypa/build
      run: >-
        python3 -m
        pip install
        build
        --user
    
    - name: Build a binary wheel and a source tarball
      run: python3 -m build
    
    - name: Store the distribution packages
      uses: actions/upload-artifact@v3
      with:
        name: python-package-distributions
        path: dist/

  publish-to-pypi:
    name: Publish to PyPI 🚀
    if: startsWith(github.ref, 'refs/tags/')  # Seulement pour les tags
    needs:
    - build
    runs-on: ubuntu-latest
    
    environment:
      name: pypi
      url: https://pypi.org/p/maxsmart
    
    permissions:
      id-token: write  # IMPORTANT: pour PyPI trusted publishing
    
    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v3
      with:
        name: python-package-distributions
        path: dist/
    
    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      # Utilise PyPI trusted publishing (pas besoin de token secret!)

  publish-to-testpypi:
    name: Publish to TestPyPI 🧪
    needs:
    - build
    runs-on: ubuntu-latest
    
    environment:
      name: testpypi
      url: https://test.pypi.org/p/maxsmart
    
    permissions:
      id-token: write
    
    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v3
      with:
        name: python-package-distributions
        path: dist/
    
    - name: Publish distribution 📦 to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
        skip-existing: true  # Skip si la version existe déjà